<?php

namespace sano\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAll() 
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT c FROM CoreBundle:comment c 
                                   GROUP BY c.post
                                   ORDER BY c.created DESC')
                    ->getResult();
    }
    
    public function getArchive($year, $month)
    {
        $fromDay = new \DateTime("$year-$month-01");
        $toDay = clone $fromDay;
        $toDay->add(new \DateInterval('P1M'));

        return $this->getEntityManager()
                            ->createQuery("SELECT c FROM CoreBundle:comment c
                                            WHERE c.created >= :minDate
                                                AND c.created < :maxDate
                                            ORDER BY c.created DESC")
                            ->setParameters(array(
                                            'minDate' => $fromDay,
                                            'maxDate'  => $toDay,
                                            ))
                            ->getResult();
    }
    public function getYearsAndMonths($limit)
    {
         return $this->getEntityManager()
                     ->createQuery("SELECT YEAR(c.created) AS year, DATE_FORMAT(c.created, '%M') AS month, c.created AS created
                                    FROM CoreBundle:comment c  
                                    GROUP BY year, month")
                     ->setMaxResults($limit)
                     ->getResult();
    }
    public function findAllByPost($id)
    {
        return $this->getEntityManager()
                     ->createQuery("SELECT c FROM CoreBundle:comment c
                                            WHERE c.post = :post
                                            ORDER BY c.created ASC")
                     ->setParameters(array(
                                     'post' => $id
                                     ))
                     ->getResult();
    }
}
